### ISSUE TITLE
2.1 branch

### ISSUE THREAD

**Issue by abretaud** [erasche/docker-tripal#24]
I've just pushed a 2.1 branch where the tripal and some of the modules versions are pinned.
For the moment there is not much difference to the master branch, but there could be in the future if some bugs are fixed/introduced in 2.x.
@erasche if you're ok could you add this branch to hub.docker.com? it looks like it's done automatically on quay.io

**Comment by hexylena** [comment]
Done.

also: do you have a docker hub account? I can add you for the future.

**Comment by abretaud** [comment]
Thanks!
I didn't have an account, but now I have :) abretaud
