### ISSUE TITLE
Tripal image build error

### ISSUE THREAD

**Issue by RichardBruskiewich** [erasche/docker-tripal#27]
In lieu of using the stock (Oct 3, 2018) docker-tripal web docker image "quay.io/erasche/tripal:v3.x" which seems to have the problem outlined in the previous submitted issue #26, I've attempted a fresh v3.x web image build using the root directory Dockerfile of the project (I'm using the v3.x branch 68d56d0e3054f8f638a8b78fe1a3affe2438a4ba commit of the code tree).

The image building progresses somewhat, mainly loading the Chado image, with some non-fatal errors along the way, mainly relating to duplicate records in the cvterm file, e.g.

_[05-Oct-2018 18:41:54 UTC] [site http://localhost:3000/tripal] [TRIPAL WARNING] [TRIPAL_CV] Failed to insert the term: Location (tripal)
ERROR (TRIPAL_CHADO): chado_insert_record; Cannot insert duplicate record into cvterm table: Array
(
    [cv_id] => 55
    [name] => Location
    [definition] => The name of the location.
    [dbxref_id] => 111751
    [is_obsolete] => 0
    [is_relationshiptype] => 0
)
_ 

until the build hits the following fatal error (message from the log):

__WD php: Error: Call to undefined function                                [error]
tripal_stock_add_organism_count_mview() in tripal_stock_install()
(line 56 of
/var/www/html/sites/all/modules/tripal/legacy/tripal_stock/tripal_stock.install).
Cannot modify header information - headers already sent by (output     [warning]
started at /root/.composer/vendor/drush/drush/includes/output.inc:40)
bootstrap.inc:1486
Error: Call to undefined function tripal_stock_add_organism_count_mview() in tripal_stock_install() (line 56 of /var/www/html/sites/all/modules/tripal/legacy/tripal_stock/tripal_stock.install).
Drush command terminated abnormally due to an unrecoverable error.       [error]
A non well formed numeric value encountered drush.inc:1643              [notice]__

**Comment by bradfordcondon** [comment]
hello, this looks like a bug in the tripal_stock legacy module: the `tripal_stock_add_organism_count_mview` should also be in the tripal_stock.install.    I'll create an issue in tripal core.

**Comment by RichardBruskiewich** [comment]
Thanks for the very swift reply Bradford!

Essentially real time...

**Comment by bradfordcondon** [comment]
hi @RichardBruskiewich no problem.  If you'd like you could try booting it off of [`tripal:09_legacy_tripal_stock_mview`](https://github.com/tripal/tripal/tree/709_legacy_tripal_stock_mview) instead of that commit and see if it gets off the ground.

**Comment by RichardBruskiewich** [comment]
Yes, I did just that - used your commit with the patch to build - and the installation procedure continued all the way to completion, thus I have a baseline running instance of the docker-compose build running this afternoon inside Docker on my Windows 10 workstation. I'm tickled pink to have reach this milestone this Friday. Thank you all again ever so much for your very quick response to my posted issues today and earlier this week. @erasche @abretaud @spficklin

**Comment by abretaud** [comment]
I think the first problem is that the docker image shouldn't try to install the old tripal_stock module. With the fix discussed in #26 it should be solved.
Thanks for testing all this!
Closing this one too, reopen if needed

**Comment by RichardBruskiewich** [comment]
Thanks Anthony and Bradford. I'll let you know how things go.
