### ISSUE TITLE
October 10th, 2018  docker-compose build error with missing elasticsearch?

### ISSUE THREAD

**Issue by RichardBruskiewich** [erasche/docker-tripal#28]
ERROR: manifest for elasticsearch:latest not found
Failed to deploy 'Compose: docker-tripal/docker-compose.yml': `docker-compose` process finished with exit code 1

Funny thing is that a specific version of elasticsearch is available:

docker pull docker.elastic.co/elasticsearch/elasticsearch:6.4.2

from https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docker.html

whereas (assuming that the default for no version is "latest"...)

 docker pull docker.elastic.co/elasticsearch/elasticsearch:latest
Error response from daemon: manifest for docker.elastic.co/elasticsearch/elasticsearch:latest not found

Maybe this is a transient error with the elasticsearch docker hub update?

I'm building today on a Mac Pro laptop (with Mac Docker) for what it is worth. As a workaround, I'll just try using 6.4.2

**Comment by RichardBruskiewich** [comment]
epilog:  Once I added the version 6.4.2, the docker-compose build continued to completion. So far, so good... It built **_sooo much faster_** on my Mac Pro laptop than my 4-1/2  year old Dell Precision 3210 workstation running Docker for Windows under Windows 10.  The baseline web site is now working, so I can perhaps start tweaking it for our project.

**Comment by abretaud** [comment]
Closing as it's working (if I understood well)

**Comment by RichardBruskiewich** [comment]
Anthony, it **only** worked (yesterday) when one added the explicit version (of 4.6.2) i.e. elasticsearch:4.6.2, to the Docker-compose.yml file. Did you make that change to the code, to fix it for others (or did the elasticsearch folks fix the “latest” tag?)

**Comment by abretaud** [comment]
Ok sorry, I know what you mean now!
I've updated the docker-compose.yml file, it was using a deprecated image for elasticsearch
Can you confirm that it's ok? I've added `TAKE_FILE_OWNERSHIP` env var, it's only needed if mounting /usr/share/elasticsearch/data, but it doesn't hurt anyway

by the way, @erasche could you grant me some permissions on https://quay.io/repository/erasche/tripal ? I can't see the build logs at the moment, it could be useful

**Comment by hexylena** [comment]
yeah of course! sorry for that oversight @abretaud

**Comment by abretaud** [comment]
thanks @erasche !

**Comment by RichardBruskiewich** [comment]
Thanks. The latest build parameters seem to work.
