### ISSUE TITLE
Clarification of environment variables?

### ISSUE THREAD

**Issue by RichardBruskiewich** [erasche/docker-tripal#33]
Colleagues,

I understand that a standard Drupal module retrieval is specified by the environment variable "TRIPAL_DOWNLOAD_MODULES" and a non-standard (git) retrieval of module code uses "TRIPAL_GIT_CLONE_MODULES" but what's the difference between the environment variables "TRIPAL_ADDITIONAL_MODULES" and "TRIPAL_ENABLE_MODULES" ?

**Comment by abretaud** [comment]
It was jut a mistake in the doc, I've updated it. Thanks for reporting!

**Comment by RichardBruskiewich** [comment]
Thanks Anthony, I figured that much since I did try the ENABLE flag to get things working.
