### ISSUE TITLE
Some warnings on Elasticsearch may need some attention?

### ISSUE THREAD

**Issue by RichardBruskiewich** [erasche/docker-tripal#40]
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

elasticsearch_1  | [2019-02-22T05:16:22,452][WARN ][o.e.c.l.LogConfigurator  ] [unknown] Some logging configurations have %marker but don't have %node_name. We will automatically add %node_name to the pattern to ease the migration for users who customize log4j2.properties but will stop this behavior in 7.0. You should manually replace `%node_name` with `[%node_name]%marker ` in these locations:

elasticsearch_1  |   /usr/share/elasticsearch/config/log4j2.properties

**Comment by abretaud** [comment]
You're using something like this: https://github.com/galaxy-genome-annotation/docker-tripal/blob/master/docker-compose.yml#L35 ?
I guess this should be checked with the [authors of the elasticsearch docker image](https://github.com/elastic/elasticsearch-docker/).
The first thing to do would be to check with an up-to-date docker image though
