### ISSUE TITLE
Need to use an init process to ensure process cleanup

### ISSUE THREAD

**Issue by hexylena** [erasche/docker-tripal#8]

**Comment by abretaud** [comment]
Hum, not sure to understand what you mean here, what is it?

**Comment by hexylena** [comment]
https://github.com/krallin/tini/issues/8 might explain it a bit.

I'm willing to bet that every time cron is triggered, drupal probably leaks processes (because it's drupal)

**Comment by abretaud** [comment]
Oh I didn't know tini, thanks for the link!
I think your assumption on drupal is valid unfortunately

**Comment by abretaud** [comment]
Done too
