### ISSUE TITLE
Need chado 1.31 for tripal 2.1

### ISSUE THREAD

**Issue by abretaud** [erasche/docker-tripal#9]
Tripal 2.1b3 needs chado >= 1.31 and currently chado 1.23 is installed from https://cpt.tamu.edu/jenkins/job/Chado-Prebuilt-Schemas/
I don't know if it would need be hard to switch to 1.31 while fixing #6?
Anyway, I will switch back to tripal 2.0 in the meantime

**Comment by hexylena** [comment]
Oh yuck.

Ok, I'll work on this this week. I need to cleanup the chado building stuff and place in an easier to hack on location.

**Comment by abretaud** [comment]
Hi Eric,
Did you find some time to work on this?

**Comment by hexylena** [comment]
Will do today. Sorry for delays.

**Comment by abretaud** [comment]
No worry! I was just wondering

**Comment by hexylena** [comment]
xref https://github.com/erasche/docker-tripal/issues/6#issuecomment-239292652

**Comment by abretaud** [comment]
And this too
